version: '2'
services:
  netty-reverse-proxy:
    build:
      context: ..
      dockerfile: Dockerfile
    image: netty-reverse-proxy:1.0.0
    restart: always
    env_file:
    - .env
    network_mode: "host"
    volumes:
    - ./log:/opt/NettyReverseProxy/App/log
    - ./reverse_proxy.properties:/opt/NettyReverseProxy/App/config/reverse_proxy.properties
    user: root
